// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Domain.Models;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public int RoleId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public virtual Role Role { get; set; }

    public virtual ICollection<CreditCard> CreditCards { get; set; } = new List<CreditCard>();
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}