// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Domain.Models;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Category
{
    public int CategoryId { get; set; }

    public int? AccountId { get; set; }

    public int TransactionTypeId { get; set; } 

    public string Title { get; set; }

    public virtual Account Account { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}