// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class CreditCard
{
    public int CreditCardId { get; set; }

    public string Number { get; set; }

    public long Expense { get; set; }

    public long Income { get; set; }

    public int AccountId { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}