// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Domain.Domain.Models;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Transaction
{
    public int TransactionId { get; set; }

    public int CreditCardId { get; set; }

    public int CategoryId { get; set; }

    public int TransactionTypeId { get; set; }

    public long Amount { get; set; }

    public string Description { get; set; }

    public DateOnly CreationDate { get; set; }

    public virtual Category Category { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual CreditCard CreditCard { get; set; }
}